# Generated by Django 2.2 on 2019-06-18 20:42

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('note', models.CharField(max_length=130)),
                ('detail', models.TextField(max_length=300)),
                ('img1', models.ImageField(upload_to=products.models.user_directory_path)),
            ],
        ),
    ]
