# Generated by Django 2.2.6 on 2019-10-17 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullAdresse', models.CharField(max_length=255)),
                ('mobiel', models.CharField(blank=True, max_length=11)),
                ('orderDate', models.DateField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('orderProduct', models.ManyToManyField(to='shopcart.productobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
