# Generated by Django 2.2.6 on 2019-10-17 20:46

from django.db import migrations, models
import imagekit.models.fields
import products.utility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('name_ar', models.CharField(max_length=15)),
                ('note', models.CharField(blank=True, max_length=130)),
                ('note_ar', models.CharField(blank=True, max_length=130)),
                ('detail', models.TextField(blank=True, max_length=300)),
                ('detail_ar', models.TextField(blank=True, max_length=300)),
                ('price', models.IntegerField()),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_1)),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_2)),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_3)),
                ('image_4', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_4)),
            ],
        ),
    ]
