# Generated by Django 2.2 on 2019-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conatact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobiel', models.CharField(blank=True, max_length=13)),
                ('subject', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='conatact_uss',
        ),
    ]
