# Generated by Django 2.2 on 2019-08-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20190830_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conatact_us',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='conatact_us',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='conatact_us',
            name='mobiel',
        ),
    ]
