# Generated by Django 2.2.6 on 2019-10-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20190831_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='conatact_us',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
