# Generated by Django 2.2 on 2019-06-23 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20190623_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('mobiel', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('streetName', models.CharField(max_length=10)),
                ('nubmerOfBuliding', models.CharField(max_length=5)),
                ('adressSing', models.CharField(max_length=25)),
                ('orderProduct', models.ManyToManyField(null=True, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
