# Generated by Django 2.2 on 2019-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adressSing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nubmerOfBuliding',
        ),
        migrations.RemoveField(
            model_name='order',
            name='streetName',
        ),
        migrations.AddField(
            model_name='order',
            name='fullAdresse',
            field=models.CharField(default=1994, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='mobiel',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderProduct',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
