# Generated by Django 2.2 on 2019-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190916_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_created=True, default='2019-09-14'),
            preserve_default=False,
        ),
    ]
