# Generated by Django 2.2 on 2019-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190623_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderProduct',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
