# Generated by Django 2.2 on 2019-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190916_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderProduct',
            field=models.ManyToManyField(to='shopcart.productobject'),
        ),
    ]
