# Generated by Django 2.2.6 on 2019-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191006_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
