# Generated by Django 2.2 on 2019-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('note', models.CharField(blank=True, max_length=130)),
                ('detail', models.TextField(blank=True, max_length=300)),
                ('image_1', models.ImageField(blank=True, upload_to='product/')),
            ],
        ),
    ]
