# Generated by Django 2.2 on 2019-06-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
    ]
