# Generated by Django 2.2 on 2019-06-23 17:32

from django.db import migrations, models
import products.utility


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190623_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=products.utility.user_directory_path_2),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=products.utility.user_directory_path_3),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=products.utility.user_directory_path_4),
        ),
    ]
