# Generated by Django 2.2 on 2019-06-27 21:35

from django.db import migrations
import imagekit.models.fields
import products.utility


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190623_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=imagekit.models.fields.ProcessedImageField(upload_to=products.utility.user_directory_path_4),
        ),
    ]
