# Generated by Django 2.2 on 2019-06-27 21:37

from django.db import migrations
import imagekit.models.fields
import products.utility


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190627_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_4),
        ),
    ]
