# Generated by Django 2.2 on 2019-06-27 21:43

from django.db import migrations
import imagekit.models.fields
import products.utility


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190627_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_2),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=products.utility.user_directory_path_3),
        ),
    ]
