# Generated by Django 2.2 on 2019-06-22 18:23

from django.db import migrations
import products.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190622_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=products.models.user_directory_path),
        ),
    ]
