# Generated by Django 2.2 on 2019-06-23 12:28

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190622_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to=products.models.user_directory_path),
        ),
    ]
