# Generated by Django 2.2 on 2019-06-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='shopCartProduct',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
