# Generated by Django 2.2 on 2019-07-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_auto_20190709_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='shopCartProduct',
            field=models.ManyToManyField(related_name='prod', to='products.product'),
        ),
    ]
