# Generated by Django 2.2 on 2019-10-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0009_auto_20191005_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobject',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
