# Generated by Django 2.2 on 2019-10-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0015_auto_20191005_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobject',
            name='quantity',
        ),
    ]
