# Generated by Django 2.2 on 2019-10-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0016_remove_productobject_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='shopCartProduct',
            new_name='shopCartProducts',
        ),
    ]
