# Generated by Django 2.2 on 2019-10-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0017_auto_20191005_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='shopCartProducts',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='shopCartProductss',
            field=models.ManyToManyField(blank=True, to='shopcart.productObject'),
        ),
    ]
