# Generated by Django 2.2 on 2019-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190817_2256'),
        ('shopcart', '0018_auto_20191005_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='shopCartProductss',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='shopCartProduct',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.DeleteModel(
            name='productObject',
        ),
    ]
