# Generated by Django 2.2 on 2019-10-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0019_auto_20191005_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='shopCartProduct',
        ),
    ]
