# Generated by Django 2.2 on 2019-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0020_remove_shopcart_shopcartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='productobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
