# Generated by Django 2.2 on 2019-10-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190817_2256'),
        ('shopcart', '0021_productobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='productobject',
            name='product',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productobject',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
