# Generated by Django 2.2 on 2019-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0022_auto_20191005_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='shopCartProduct',
            field=models.ManyToManyField(blank=True, to='shopcart.productobject'),
        ),
    ]
